server.port=${PORT:8080}
info.app.name=spring
info.app.description=This is my first spring boot application
info.app.version=1.0.0

vaadin.frontend.hotdeploy=true
vaadin.productionMode=false

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
logging.level.root=error

#activemq
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.packages.trust-all=true
#message converter can convert and serialize the message I created and won't give exception that i dont trust this typoe

